# base image
FROM node:16.14.2-alpine3.14

# make folder to put files and set it as working directory
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/client
WORKDIR /usr/src/app/client

# copy package.json and package-lock.json and install dependencies
COPY package*.json ./
RUN npm install

# copy all files
COPY . .
# RUN npm run build

# expose port 3000 to access the server
EXPOSE 3000

# command to run the server
# CMD [ "npm", "run", "start" ]