version: "3.7"

services:
    # # create a container for the client
    # client: # name of the service/container
    #     build: ./client # path to the Dockerfile
    #     ports:
    #         - "3000:3000" # port mapping
    #     container_name: bloghive-client # name of the container
    #     restart: always # restart the container if it crashes
    #     links:
    #         - server # link to the server container

    # # create a container for the server
    # server:
    #     build: ./server
    #     ports:
    #         - "8000:8000"
    #     container_name: bloghive-server
    #     restart: always
    #     links:
    #         - db # link to the db container

    # create a container for the database
    db:
        image: postgres # use the official postgres image
        restart: always
        environment:
            POSTGRES_PASSWORD: root # set the password for the postgres user
            POSTGRES_USER: postgres # set the username for the postgres user
        ports:
            - "5432:5432"
        # name of the container
        container_name: bloghive-db
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
